project:
  type: website
  output-dir : docs  
website:
  title: "C.I.C"
  page-navigation: true
  sidebar:
    style: "docked"
    search: True
    contents: auto
    
format:
  html:
    css: styles.css
    toc: true
    code-fold : False
    code-line-numbers : True
    code-copy : True

theme :
  light : flatly
  
editor : visual